language: python
python: 2.7

before_install:
- openssl aes-256-cbc -K $encrypted_0f3d298afe4e_key -iv $encrypted_0f3d298afe4e_iv
  -in deploy_key.pem.enc -out deploy_key.pem -d

install:
  - pip install -r requirements.txt

script:
  - echo noop

deploy:
  provider: script
  script:
    - ./deploy.sh
  on:
    branch: source
