#!/usr/bin/env python3
"""
Sync the Music page with the latest videos from the YouTube "Compositions"
playlist RSS feed.

Regenerates only the block between MUSIC_LIST_START / MUSIC_LIST_END markers
in site/pages/music.md, leaving the hand-written intro untouched. Idempotent:
re-running with unchanged playlist data produces no diff.
"""

import html
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

PLAYLIST_ID = "PL2ifqcLphtAiSrhDFKL_7sV-_HuLFvVzL"
FEED_URL = f"https://www.youtube.com/feeds/videos.xml?playlist_id={PLAYLIST_ID}"

BASE_DIR = Path(__file__).resolve().parent.parent
MUSIC_PAGE = BASE_DIR / "site" / "pages" / "music.md"

START_MARKER = "<!-- MUSIC_LIST_START -->"
END_MARKER = "<!-- MUSIC_LIST_END -->"
GENERATED_NOTICE = "<!-- This section is auto-generated by manage/sync_music.py. Do not edit by hand. -->"

ATOM_NS = "{http://www.w3.org/2005/Atom}"
YT_NS = "{http://www.youtube.com/xml/schemas/2015}"

TITLE_SUFFIX_RE = re.compile(r"\s*-\s*a music piece\s*$", re.IGNORECASE)


def fetch_feed(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "sync_music.py"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        return resp.read()


def clean_title(title: str) -> str:
    return TITLE_SUFFIX_RE.sub("", title).strip()


def parse_entries(xml_bytes: bytes) -> list[dict]:
    root = ET.fromstring(xml_bytes)
    entries = []
    for entry in root.findall(f"{ATOM_NS}entry"):
        video_id = entry.findtext(f"{YT_NS}videoId")
        title = entry.findtext(f"{ATOM_NS}title", "").strip()
        published = entry.findtext(f"{ATOM_NS}published", "")
        if not video_id or not title:
            continue
        entries.append({
            "video_id": video_id,
            "title": clean_title(title),
            "published": published,
        })
    entries.sort(key=lambda e: e["published"], reverse=True)
    return entries


def render_block(entries: list[dict]) -> str:
    lines = [START_MARKER, GENERATED_NOTICE, ""]
    for e in entries:
        title_attr = html.escape(e["title"], quote=True)
        lines.append(f"### {e['title']}")
        lines.append("")
        lines.append('<div class="video-embed">')
        lines.append(
            f'<iframe src="https://www.youtube.com/embed/{e["video_id"]}" '
            f'title="{title_attr}" frameborder="0" allowfullscreen></iframe>'
        )
        lines.append("</div>")
        lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def replace_block(content: str, new_block: str) -> str:
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if not pattern.search(content):
        raise ValueError(
            f"Markers {START_MARKER!r} / {END_MARKER!r} not found in {MUSIC_PAGE}"
        )
    return pattern.sub(new_block, content)


def main() -> int:
    content = MUSIC_PAGE.read_text(encoding="utf-8")

    xml_bytes = fetch_feed(FEED_URL)
    entries = parse_entries(xml_bytes)
    print(f"Fetched {len(entries)} videos from playlist feed")

    new_block = render_block(entries)
    new_content = replace_block(content, new_block)

    if new_content == content:
        print("No changes.")
        return 0

    MUSIC_PAGE.write_text(new_content, encoding="utf-8")
    print(f"Updated {MUSIC_PAGE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
